# Generated by Django 5.2.5 on 2025-08-20 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 20, 13, 29, 33, 161923, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(default=1, upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
