# Generated by Django 5.2.5 on 2025-08-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0002_car_create_date_car_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
