# Generated by Django 5.2.5 on 2025-08-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0005_alter_car_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
